hw5 modal
js-tasks-ru/htmlcss-20230911-4_info91 pull request #11
Opened 2023-09-27 08:32 UTC by consultapp

2023-09-27 08:39 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-09-27 21:03 UTC, GSemikozov requested changes

2023-09-27 21:03 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +          <p class="modal__title">Modal title</p>
если тайтл, тогда например h3

2023-09-27 21:03 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  position: fixed;
все что здесь - уносим на уровень блока, а элемент удаляем

2023-09-28 06:37 UTC, consultapp commented on 05-lection3/02-modal/index.html
> +          <p class="modal__title">Modal title</p>
мне не хотелось что бы модалка учавствовала в ceo просто. h3 будет же включен в структуру.

2023-09-28 06:38 UTC, consultapp commented on 05-lection3/02-modal/modal.css
> +  position: fixed;
Тогда скрипт display переписывает при открытии / закрытии

2023-09-28 06:39 UTC, consultapp commented on 05-lection3/02-modal/modal.css
> +  position: fixed;
Надо исправить центрирование контента - не на флексе?

2023-09-28 20:47 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +          <p class="modal__title">Modal title</p>
а `p` - нет?)
тогда лучше div.

2023-09-28 20:49 UTC, GSemikozov requested changes

2023-09-28 20:49 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  position: fixed;
тогда можно и в самом скрипте поправить

2023-09-28 20:49 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  position: fixed;
центрирование окна модалки внутри блока - ок, дальше только на более мелких экранах надо будет улучшить

2023-09-29 08:58 UTC, consultapp commented on 05-lection3/02-modal/index.html
> +          <p class="modal__title">Modal title</p>
сменил все на див

2023-09-29 08:58 UTC, consultapp commented on 05-lection3/02-modal/modal.css
> +  position: fixed;
исправил в скрипте, убрал wrapper.

2023-10-01 19:14 UTC, GSemikozov approved these changes

2023-10-01 19:14 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2023-10-02 19:37 UTC, GSemikozov approved these changes

2023-10-02 19:37 UTC, merged