avatar
js-tasks-ru/htmlcss-20230911-4_info91 pull request #16
Opened 2023-10-06 08:28 UTC by consultapp

2023-10-06 08:28 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-10-07 21:39 UTC, GSemikozov requested changes

2023-10-07 21:39 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +.avatar {
а размеры блока?)

2023-10-08 07:22 UTC, consultapp commented on 06-lection4/01-avatar/avatar.css
> +.avatar {
указал.

2023-10-08 16:34 UTC, GSemikozov approved these changes

2023-10-08 16:34 UTC, merged