hw8 input text
js-tasks-ru/htmlcss-20230911-4_info91 pull request #22
Opened 2023-10-08 12:32 UTC by consultapp

2023-10-08 12:32 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-10-10 20:12 UTC, GSemikozov requested changes

2023-10-10 20:12 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +      <label class="inputText"
для начала пройдемся по структуре:
1) в случае с инпутом не надо все заворачивать в лейбл - это просто отдельный элемент
2) собственно текст надо завернуть в лейбл
3) инпут надо завернуть в общий с иконками
4) иконки лучше добавить как отдельный хтмл-элементы, чтобы сохранять все возможности работы с свг

2023-10-11 18:25 UTC, consultapp commented on 07-lection5/04-input/index.html
> +      <label class="inputText"
Все исправил. Не понял как тогда быть с БЭМ, если нет общего враппера.

Все работает, но теперь все inline и что бы не улетали иконки и прочее с этим при вставке надо бороться.

2023-10-13 21:38 UTC, GSemikozov requested changes

2023-10-13 21:38 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +      <label class="inputText"
все еще не исправлено (см пункт 1).

что именно инлайн?) div или label?

2023-10-14 06:15 UTC, consultapp commented on 07-lection5/04-input/index.html
> +      <label class="inputText"
Не понял, я вынес label за враппер. В п1 написано, что не надо оборачивать инпут в лейбл.
Вопрос надо для них делать общий враппер или нет.

что именно инлайн?) div или label? - оба, что бы нажатия не было мимо них..

2023-10-15 04:56 UTC, consultapp commented on 07-lection5/04-input/index.html
> +      <label class="inputText"
Локальную копию получается не потянул. Сейчас 2 pr почему-то создалось на 1 ветку.

2023-10-15 12:51 UTC, merged