Hw8 input text
js-tasks-ru/htmlcss-20230911-4_info91 pull request #25
Opened 2023-10-15 04:48 UTC by consultapp

2023-10-15 04:48 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-10-15 04:54 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-10-15 12:50 UTC, GSemikozov requested changes

2023-10-15 12:50 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +    <label class="inputText__label" for="input1">Lable: </label>
элементы не могут болтаться сами по себе, их надо завернуть в общий div с классом того блока которому они принадлежат

2023-10-18 16:12 UTC, consultapp commented on 07-lection5/04-input/index.html
> +    <label class="inputText__label" for="input1">Lable: </label>
прлил изменения из локального гита

2023-10-22 18:27 UTC, GSemikozov requested changes

2023-10-22 18:27 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.inputText__successIcon {
.inputText__successIcon + .inputText__errorIcon => это все один элемент .inputText__Icon, а показываем нружную через модификаторы по типу .inputText__icon_error

2023-10-23 13:15 UTC, consultapp commented on 07-lection5/04-input/input.css
> +.inputText__successIcon {
Исправил.

2023-10-25 18:40 UTC, GSemikozov approved these changes

2023-10-25 18:41 UTC, merged