burger
js-tasks-ru/htmlcss-20230911-4_info91 pull request #29
Opened 2023-10-25 19:14 UTC by consultapp

2023-10-25 19:15 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-10-29 20:24 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-10-31 10:10 UTC, GSemikozov requested changes

2023-10-31 10:10 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +  display: block;
flex?

2023-10-31 10:10 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +    overflow: scroll;
и слева и справа? или только по вертикали?

2023-10-31 10:10 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +    height: 100%;
vh

2023-10-31 10:10 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +  .navigation__themeTogglerWrapper {
переключалку лучше не делать в этой задаче. Либо тогда как отдельный компонент

2023-10-31 21:21 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-01 07:58 UTC, consultapp commented on 09-lection7/01-burger-menu/burger-menu.css
> +  display: block;
поменял

2023-11-01 07:59 UTC, consultapp commented on 09-lection7/01-burger-menu/burger-menu.css
> +    overflow: scroll;
вертикаль. исправил

2023-11-01 07:59 UTC, consultapp commented on 09-lection7/01-burger-menu/burger-menu.css
> +    height: 100%;
исправил

2023-11-01 08:00 UTC, consultapp commented on 09-lection7/01-burger-menu/burger-menu.css
> +  .navigation__themeTogglerWrapper {
я поменял названия и добавил сам переключатель. Переключатель сделан компонентом, это просто его позиционирование в навигационном блоке.

2023-11-01 08:02 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-01 16:54 UTC, GSemikozov approved these changes

2023-11-01 16:54 UTC, merged