Hw 3 index main blocks
js-tasks-ru/htmlcss-20230911-4_info91 pull request #4
Opened 2023-09-16 09:15 UTC by consultapp

2023-09-16 09:16 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-09-16 20:52 UTC, GSemikozov requested changes

2023-09-16 20:52 UTC, GSemikozov commented on assets/css/main.css
> +h1 {
все блоки и элементы должны быть описаны как компоненты в папке components, никаких глобальных стилей (почти) не пишем ;)

2023-09-17 20:27 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-09-17 20:28 UTC, consultapp commented on assets/css/main.css
> +h1 {
Переделал на components.

2023-09-18 21:57 UTC, GSemikozov approved these changes

2023-09-18 21:57 UTC, merged