Hw4 main page +  cards
js-tasks-ru/htmlcss-20230911-4_info91 pull request #7
Opened 2023-09-23 12:23 UTC by consultapp

Hw4 main page update +  cards

2023-09-23 12:23 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-09-24 22:14 UTC, GSemikozov requested changes

2023-09-24 22:14 UTC, GSemikozov commented on components/footer/footer.css
> +.footer__p {
.footer__text (привязываться к тегам в именах классов плохая практика)

2023-09-24 22:14 UTC, GSemikozov commented on components/header/header.css
> +.header h1 {
.header__title

2023-09-24 22:14 UTC, GSemikozov commented on components/header/header.css
> +.header__topMenu * {
проще создать класс элемента и ему задавать этот стиль

2023-09-24 22:14 UTC, GSemikozov commented on components/header/header.css
> +.header__nav li {
.header__list-item

2023-09-24 22:14 UTC, GSemikozov commented on components/header/header.css
> +.header__nav ul {
.header__list (.header__nav-list)

2023-09-24 22:14 UTC, GSemikozov commented on components/preview/preview.css
> +.preview__item_caption {
просто отдельный элемент

2023-09-24 22:14 UTC, GSemikozov commented on components/preview/preview.css
> +.preview__item_type {
и это

2023-09-25 07:40 UTC, consultapp commented on components/footer/footer.css
> +.footer__p {
+

2023-09-25 07:41 UTC, consultapp commented on components/header/header.css
> +.header h1 {
+

2023-09-25 07:47 UTC, consultapp commented on components/header/header.css
> +.header__topMenu * {
+

2023-09-25 07:47 UTC, consultapp commented on components/header/header.css
> +.header__nav li {
+

2023-09-25 07:47 UTC, consultapp commented on components/header/header.css
> +.header__nav ul {
исправил

2023-09-25 07:51 UTC, consultapp commented on components/preview/preview.css
> +.preview__item_caption {
ошибся в нейминге

2023-09-25 07:51 UTC, consultapp commented on components/preview/preview.css
> +.preview__item_type {
ошибся в нейминге

2023-09-25 21:02 UTC, GSemikozov approved these changes

2023-09-25 21:02 UTC, merged